### PR TITLE
FIX VND

### PR DESCRIPTION
**Pull request by borel**
Sorry , but my PR from yesterday was a mistake.
It's 2 decimalDigits ( https://www.thefinancials.com/Default.aspx?SubSectionID=curformat ) and not 3

### CODE REVIEW

**Comment by smirzaei** [comment]
The interesting thing is, the built-in intl API doesn't display decimal points.

```js
new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(1.5)
"2 ₫"

new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(1.4)
"1 ₫"
```

**Comment by smirzaei** [comment]
One small issue... `.` is the correct decimal separator.

```js
new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(100000000)
"100.000.000 ₫"
```

**Comment by borel** [comment]
I think there is no decimal in this currency

**Comment by smirzaei** [comment]
Looks good, thanks.

**Pull request merged**
