### PR TITLE
Use ES5 functions instead of arrow functions

### LINKED ISSUE #1: Arrow function
Everything seems to be ES5 except the use of an error function

line 16:
```
var currency = data.find(c => c.code === options.code) || this.defaultCurrency;
```

line 42:
```
return data.find(c => c.code === currencyCode);
```

### PR DESCRIPTION
**Pull request by BurntCaramel**
Fixes #1

### CODE REVIEW

**Comment by smirzaei** [comment]
Thanks for the commit, but what is it trying to accomplish exactly? I mean what is the problem with using arrow functions? it is supported since node version `0.11` which was released in early 2013 I think.

If you're trying to use it in an earlier version, we can accept this and also we would need to change the `Array#find` method, since it is also a part of `ES6.

**Comment by smirzaei** [comment]
But I also don't see any harm in it.

Thanks for the commit :+1:

**Comment by BurntCaramel** [comment]
It was to use in a browser with browserify!

**Comment by smirzaei** [comment]
Ah! okay... I also updated the NPM. Let me know if you run into any issues :)

**Pull request merged**
