### PR TITLE
Added XBT currency

### PR DESCRIPTION
**Pull request by smirzaei**
Added the `XBT` currency and left `BTC` there so it wouldn't break the older clients.
Feel free to send a PR if it's incorrect.

#53

### CODE REVIEW

**Comment by AlexWayfer** [comment]
`package-lock.json` added. :thinking:

**Comment by smirzaei** [comment]
> package-lock.json added. :thinking:

Is there a problem with checking in the `package-lock.json` file? I did a quick search before committing it and it seemed okay.

https://stackoverflow.com/a/44210813/980103

**Comment by AlexWayfer** [comment]
Sorry, I mean I was not sure that was added deliberately or accidentially. Doesn't look related to the subject of this PR. If deliberately — OK, no problem.

But… there is opinion about lock-files: [Lockfiles for apps, but not for packages](https://github.com/sindresorhus/ama/issues/479).

What is purpose of this file? Dependencies with versions locking (major, minor, patch) should be listed in `package.json`.

**Comment by smirzaei** [comment]
Yeah I cloned the repo on a new machine. I guess that's why it added that file. Anyways if it's causing a problem let me know and I'll remove it.

**Comment by edorivai** [comment]
I think @AlexWayfer has a good point. [Quote](https://github.com/sindresorhus/ama/issues/479#issuecomment-310661514) from Sindre Sorhus:

> Lockfiles for apps, but not for packages. Lockfiles are great for apps where you want a controlled reproducible environment, but for packages this doesn't make much sense. The package-lock.json files in dependencies are ignored, so the lockfile only applies when users run npm install in the package repo. If you use a lockfile for packages, your local dependency tree will not match the dependency tree of users having your package as a dependency. This can potentially cause problems if one of your package dependencies breaks your package in a patch release. The lockfile will prevent you from seeing the problem locally, but it will affect your users.

I would refrain from committing the lockfile here.

**Comment by AlexWayfer** [comment]
> This can potentially cause problems if one of your package dependencies breaks your package in a patch release. The lockfile will prevent you from seeing the problem locally, but it will affect your users.

Yes, that's what I means :grimacing: 

It would be cool if repo will has the same flexibillity and reproducable, as a final package for regular users. There are can be different flaws in `package.json`, hidden from developers by `package-lock.json`.

**Comment by smirzaei** [comment]
Alright fair enough, I'll take care of it soon! :)

**Pull request merged**
